spring:
  datasource:
    url: jdbc:mysql://legossol.crrrqqjyomfc.ap-northeast-2.rds.amazonaws.com/ssol?serverTimezone=UTC&characterEncoding=UTF-8
    username: legossol
    password: haesol21
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      